### ISSUE TITLE
install failed on 8.0

### ISSUE THREAD

**Issue by aircable** [aliomattux/omniship#2]
Hi, thanks for your module, I've been working on it for a while and got all dependencies resolved.
But now we have a problem with dependencies for 8.0.
It failed with: KeyError: 'stock.out.package'

And looking through Odoo 8.0 there is no object you can inherit from:

class StockOutPackage(osv.osv):
    _inherit = 'stock.out.package'
    def _make_name(self, cr, uid, ids, name, unknown, context=None):

Any solution?

**Comment by aliomattux** [comment]
you need the module stock_package which is available in my repositories.

**Comment by aircable** [comment]
thanks, got it, and got the payment_method module too, both installed ok

next is suds, but my Python has suds installed.
see, this is from the python command line to check, of course, the report
isn't there from command line.

But why would authorizenet module report that suds isn't there?

>>> import suds;
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "build/bdist.macosx-10.10-intel/egg/suds/__init__.py", line 149, in
<module>
  File "build/bdist.macosx-10.10-intel/egg/suds/client.py", line 24, in
<module>
  File
"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/cookielib.py",
line 38, in <module>
    from calendar import timegm
  File "calendar/__init__.py", line 22, in <module>
    from . import calendar
  File "calendar/calendar.py", line 7, in <module
    import openerp.service.report
ImportError: No module named report

**Comment by lukebranch** [comment]
@aliomattux ,

Thanks for your work on this awesome module! I'm having issues getting it to install in 8.0 on Ubuntu 12.04. Here's the traceback:

```
Traceback (most recent call last):
  File "/opt/odoo/odoo-server/openerp/http.py", line 530, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo-server/openerp/http.py", line 567, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/odoo-server/openerp/http.py", line 303, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/odoo-server/openerp/service/model.py", line 113, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/odoo-server/openerp/http.py", line 300, in checked_call
    return self.endpoint(*a, **kw)
  File "/opt/odoo/odoo-server/openerp/http.py", line 796, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/odoo-server/openerp/http.py", line 396, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/odoo-server/addons/web/controllers/main.py", line 953, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/odoo/odoo-server/addons/web/controllers/main.py", line 941, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/opt/odoo/odoo-server/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/odoo-server/openerp/addons/base/module/module.py", line 450, in button_immediate_install
    return self._button_immediate_function(cr, uid, ids, self.button_install, context=context)
  File "/opt/odoo/odoo-server/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/odoo-server/openerp/addons/base/module/module.py", line 498, in _button_immediate_function
    registry = openerp.modules.registry.RegistryManager.new(cr.dbname, update_module=True)
  File "/opt/odoo/odoo-server/openerp/modules/registry.py", line 366, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/odoo/odoo-server/openerp/modules/loading.py", line 355, in load_modules
    loaded_modules, update_module)
  File "/opt/odoo/odoo-server/openerp/modules/loading.py", line 255, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/opt/odoo/odoo-server/openerp/modules/loading.py", line 143, in load_module_graph
    load_openerp_module(package.name)
  File "/opt/odoo/odoo-server/openerp/modules/module.py", line 315, in load_openerp_module
    __import__('openerp.addons.' + module_name)
  File "/opt/odoo/odoo-server/openerp/modules/module.py", line 80, in load_module
    mod = imp.load_module('openerp.addons.' + module_part, f, path, descr)
  File "/opt/odoo/custom/addons/omniship/__init__.py", line 2, in <module>
    import models
  File "/opt/odoo/custom/addons/omniship/models/__init__.py", line 3, in <module>
    import ups_api
  File "/opt/odoo/custom/addons/omniship/models/ups_api.py", line 2, in <module>
    from ups import ShipmentConfirm, ShipmentAccept, ShipmentVoid, PyUPSException
ImportError: No module named ups
```

i've added stock_package to my addons directory, and sudo python setup.py install for the ups module.

Is there something i'm missing?

**Comment by aliomattux** [comment]
Yes,

The error is clear: The UPS module is not installed or not installed
correctly. When you installed the UPS module did you restart the openerp
server? You should also make sure you are using the UPS module from my
repository.

**Comment by lukebranch** [comment]
@aliomattux ,

Thanks for the quick reply. Here are the repositories i've used:

Branch:      Repository:
Master:       https://github.com/aliomattux/omniship
Master:       https://github.com/aliomattux/stock_package
Master:       https://github.com/aliomattux/ups

I've installed them in the following directories and symlinked them:

Directory:                                          Symlink:
/opt/odoo/custom/omniship              /opt/odoo/custom/addons/omniship
/opt/odoo/custom/stock_package    /opt/odoo/custom/addons/stock_package
/opt/odoo/custom/ups                      /opt/odoo/custom/addons/ups

I've also run: 
sudo python setup.py install 
in 
/opt/odoo/custom/ups/setup.py

Once this was done I restarted openerp-server (i'm running in gevent-mode) and installed omniship.

I've only just noticed this repository:

Master:       https://github.com/aliomattux/py-endicia

Should I install this as well?

**Comment by aliomattux** [comment]
Yes, you should also have the py-endicia module installed. Currently both
modules UPS/Py-endicia are required even if you only intend to use 1
carrier.

You do not need to symlink these modules at all. The UPS/Py-endicia are
python library modules and only need to be installed on your system. If you
still face the error, perhaps they are not installed successfully? Only the
stock_package and omniship modules are actual Odoo modules.

**Comment by lukebranch** [comment]
@aliomattux ,

I wondered about the ups module being a library, i'll remove the symlinks for those. 

I'll install py-endica and report back if I run into any issues.

Thanks for your help.

**Comment by lukebranch** [comment]
@aliomattux ,

Sorry to bother you again. I've run into another traceback while installing omniship:

```
Traceback (most recent call last):
  File "/opt/odoo/odoo-server/openerp/http.py", line 530, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo-server/openerp/http.py", line 567, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/odoo-server/openerp/http.py", line 303, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/odoo-server/openerp/service/model.py", line 113, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/odoo-server/openerp/http.py", line 300, in checked_call
    return self.endpoint(*a, **kw)
  File "/opt/odoo/odoo-server/openerp/http.py", line 796, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/odoo-server/openerp/http.py", line 396, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/odoo-server/addons/web/controllers/main.py", line 953, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/odoo/odoo-server/addons/web/controllers/main.py", line 941, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/opt/odoo/odoo-server/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/odoo-server/openerp/addons/base/module/module.py", line 450, in button_immediate_install
    return self._button_immediate_function(cr, uid, ids, self.button_install, context=context)
  File "/opt/odoo/odoo-server/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/odoo-server/openerp/addons/base/module/module.py", line 498, in _button_immediate_function
    registry = openerp.modules.registry.RegistryManager.new(cr.dbname, update_module=True)
  File "/opt/odoo/odoo-server/openerp/modules/registry.py", line 366, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/odoo/odoo-server/openerp/modules/loading.py", line 355, in load_modules
    loaded_modules, update_module)
  File "/opt/odoo/odoo-server/openerp/modules/loading.py", line 255, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/opt/odoo/odoo-server/openerp/modules/loading.py", line 176, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "/opt/odoo/odoo-server/openerp/modules/loading.py", line 118, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/opt/odoo/odoo-server/openerp/tools/convert.py", line 901, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/opt/odoo/odoo-server/openerp/tools/convert.py", line 987, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/opt/odoo/odoo-server/openerp/tools/convert.py", line 857, in parse
    raise ParseError, (misc.ustr(e), etree.tostring(rec).rstrip(), rec.getroottree().docinfo.URL, rec.sourceline), exc_info[2]
ParseError: "null value in column "carrier" violates not-null constraint
DETAIL:  Failing row contains (2, 1, 2015-02-28 09:24:45.079085, USPS Sm Flat, null, 1.750, 5.500, 8.500, null, 2015-02-28 09:24:45.079085, 1).
" while parsing /opt/odoo/custom/addons/omniship/data/services.xml:5, near
<record id="mailpiece_dimensions_01" model="delivery.box.shape">
            <field name="name">USPS Sm Flat</field>
            <field name="length">8.5</field>
            <field name="width">5.5</field>
            <field name="height">1.75</field>
        </record>
```

**Comment by aliomattux** [comment]
Not sure on this one, This module needs to be updated by me.

Can you comment out the data file in __openerp__.py

Comment out the services.xml file. Then it should install. Looks like you
got past the other error

**Comment by lukebranch** [comment]
@aliomattux ,

Thanks for your help. I guess I can run my own local fork of this without this part of services.xml, as it is only creating pre-defined Box Shape/Dimensions right?

I'm not sure why my instance is throwing that error with that block intact, but it seems to install without any issues with it commented out.

**Comment by moturi12** [comment]
Hi Kyle - I also got the error with the default dimensions

ParseError: "null value in column "carrier" violates not-null constraint
DETAIL:  Failing row contains (1, 1, 2015-03-01 11:29:39.787742, USPS Sm Flat, null, 1.750, 5.500, 8.500, null, 2015-03-01 11:29:39.787742, 1).
" while parsing /opt/odoo/additional_addons/omniship/data/services.xml:5, near
<record id="mailpiece_dimensions_01" model="delivery.box.shape">
            <field name="name">USPS Sm Flat</field>
            <field name="length">8.5</field>
            <field name="width">5.5</field>
            <field name="height">1.75</field>
        </record>

**Comment by aliomattux** [comment]
Hi,

There is a problem with the services.xml file. If you comment this file out in __openerp__.py you can install the module without error. I am not currently developing this module, however I will return in a while to update its codebase and fix errors.

**Comment by moturi12** [comment]
Thanks Kyle. Yes I did the same and installed with out any issues. I was hoping to extend the module to integrate with a freight brokering system ( smartfreight. com) bit looks like this implementation is different what I was hoping to do.


Cheers,

Naran

Sent from Yahoo7 Mail on Android

**Comment by aliomattux** [comment]
Please do explain in detail what about the module you wish was different.

**Comment by moturi12** [comment]
Hi Kyle - Firstly , My requirement is to integrate with freight broker software api's through wsdl endpoints and business requirements is a two stage process :- 
1) Based on the Weight & Dimensions & Destination, it should return all the available carrier options along with pricing options2) Based on the user confirmation, it locks the carrier and send carrier confirmation to the system, which process the labels and returns the labels as image and tracking number.
I have seen similar module done but only for FedEx, couldn't able to find it.
Cheers,Naran 

     On Tuesday, 3 March 2015, 19:58, Kyle Waid <notifications@github.com> wrote:
   

 Please do explain in detail what about the module you wish was different.—

**Comment by ryepdx** [comment]
I'm working on something like that over in my fork. In particular, I'm setting up Omniship to grab shipping quotes from USPS, UPS, and FedEx based on weight and destination, display the quotes as shipping options during the website's checkout process, and then allow purchasing and printing labels for each package in the shipment during the shipping process.

**Comment by lukebranch** [comment]
@ryepdx ,

That looks very useful, I could definitely use the checkout process functionality in one of my projects. Is this the fork you are referring to?:

https://github.com/ryepdx/omniship

@aliomattux ,

I think these contributions would be a valuable addition to the omniship project, as I know a number of Odoo users that sell multi-channel (B2B, B2C). A frontend checkout process option would definitely come in handy for a few of these projects.

**Comment by ryepdx** [comment]
Yes, that's the fork I was referring too. Hoping to have a functional PR for you later today, with a bit of luck! I'm going to have to fudge a few things initially, though, since I don't know of a way to easily determine at checkout how many packages it will take to ship an item and how big they will each be. (The idea is to have the system automatically buy the postage when checkout completes.)

**Comment by lukebranch** [comment]
@ryepdx ,

Thanks, i'm looking forward to seeing what you've built! I will be putting together a pilot e-commerce project soon and would be happy to do some extensive testing on this functionality once it's ready.

I've used other auto-shipping calculation frameworks in the past and most of them have offered a set of options to the frontend customer, and a complete list of options for the backend user with the option the customer selected in the frontend highlighted in some fashion.

You may want to take a look at Temando shipping (for Magento), as from memory I think these guys had a pretty good setup, with bookings organised directly from Magento:

http://www.magentocommerce.com/magento-connect/temando-shipping-extension-2014.html

**Comment by aliomattux** [comment]
Hi,

If you are going to create a feature that does quotes or any functionality
on the ecommerce side, I would recommend that you create a separate module
with dependency on the omniship module. There will be lots of companies
using this module that will not be using Odoo ecommerce.

Kyle

**Comment by lukebranch** [comment]
+1,

I agree, it would definitely be preferable to have the module as an extension of the base module, rather than a part of the core.
